name: pyrsr
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - numpy>=1.22
  - matplotlib>=3.5
  - scipy>=1.8
  - astropy>=5.0
  - uncertainties>=3.1.7
  - pytest>=7.0
  - pytest-cov
  - black
  - pip
